### PR TITLE
Add MaaS testing support

### PR DESCRIPTION
**Pull request by git-harry**
This commit enables the use of the test-maas.yml playbook being added
to rpc-openstack and makes the following changes:

The variable test_monitoring is added to the openstack_multi_node.yml
template and jenkins/stack-create.sh.

The following variables are added/modified in user_extra_variables.yml
using config_controller_primary.sh:
- ssl_check
- hp_check
- maas_horizon_scheme
- maas_testing_mappings
- maas_testing_task_files

### CODE REVIEW

**Comment by mattt416** [comment]
Testing this out now.  Once confirmed I'll update https://github.com/rcbops/rpc-heat/blob/master/jenkins/stack-test.sh to run this instead of rpc-maas-tool.py.

**Comment by mattt416** [comment]
Need to wait for https://github.com/rcbops/rpc-openstack/pull/217 to merge before we can merge this PR.

**Comment by mancdaz** [comment]
To save anyone else checking, that above PR has indeed merged. This PR can now be tested properly

**Comment by mancdaz** [comment]
I have tested this. It works, in that it showed errors in the maas setup that are genuine errors. I vote on merging this and then going and updating the references inside rpc-openstack to fix those errors.

And by 'genuine errors' I just mean that there are new checks/alarms that we do not have in the reference file, so the testing shows them up as 'I do not know about these therefore they shouldn't be here'

:+1:

**Pull request merged**
